version: "3.4"

x-common-variables: &common-variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

volumes:
  pg_sandbox_data:
  pg_development_data:

services:
  db:
    image: postgres:11.2
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - "pg_${PLAID_ENV}_data:/var/lib/postgresql/data"
    ports:
      - 5433:5432
    environment: *common-variables

  server:
    build: ./server
    image: plaidinc/pattern-server:1.0.7
    ports:
      - 5001:5001
    environment:
      <<: *common-variables
      PLAID_CLIENT_ID:
      PLAID_SECRET_SANDBOX:
      PLAID_SECRET_DEVELOPMENT:
      PLAID_SANDBOX_REDIRECT_URI:
      PLAID_DEVELOPMENT_REDIRECT_URI:
      PLAID_ENV:
      PORT: 5001
      DB_PORT: 5432
      DB_HOST_NAME: db
    depends_on:
      - db

  ngrok:
    image: ngrok/ngrok:latest
    command: ["start", "--all", "--config", "/etc/ngrok.yml"]
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok.yml
      - ./ngrok/combined.pem:/etc/combined.pem
#      - ./ngrok/corp-fin-rsa-sha256-Infrastructure-CA.pem:/etc/corp-fin-rsa-sha256-Infrastructure-CA.pem
#      - ./ngrok/corp-fin-rsa-sha256-Root-CA.pem:/etc/corp-fin-rsa-sha256-Root-CA.pem
#      - ./ngrok/ZscalerSSL.pem:/etc/ZscalerSSL.pem
    ports:
      - 4040:4040
    depends_on:
      - server

  client:
    build: ./client
    image: plaidinc/pattern-client:1.0.7
    ports:
      - 3001:3001
    environment:
      REACT_APP_PLAID_ENV: ${PLAID_ENV}
      REACT_APP_SERVER: http://localhost:5001
      REACT_APP_SERVER_PORT: 5001
    depends_on:
      - server
