version: "3.4"

x-common-variables: &common-variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

volumes:
  pg_sandbox_data:
  pg_development_data:

services:
  db:
    image: postgres:11.2
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - "pg_${PLAID_ENV}_data:/var/lib/postgresql/data"
    ports:
      - 5433:5432
    environment: *common-variables

  server:
    build: ./server
    image: plaidinc/pattern-server:1.0.7
    ports:
      - 5001:5001
    environment:
      <<: *common-variables
      PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
      PLAID_SECRET_SANDBOX: ${PLAID_SECRET_SANDBOX}
      PLAID_SECRET_DEVELOPMENT: ${PLAID_SECRET_DEVELOPMENT}
      PLAID_SANDBOX_REDIRECT_URI: ${PLAID_SANDBOX_REDIRECT_URI}
      PLAID_DEVELOPMENT_REDIRECT_URI: ${PLAID_DEVELOPMENT_REDIRECT_URI}
      PLAID_WEBHOOK_URL: https://smee.io/HHrCPr4m2SbzfJJ
      PLAID_ENV: sandbox
      PORT: 5001
      DB_PORT: 5432
      DB_HOST_NAME: db
    depends_on:
      - db
#  smee:
#    build: ./smee
#    image: smee
#    ports:
##      - "5001:5001"
#      - "50000:50000"
#    environment:
#      PORT: 8081
#    command: ["-u", "https://smee.io/HHrCPr4m2SbzfJJ", "-t", "http://server:5001/services/webhook"]
#    depends_on:
#      - server
  client:
    build: ./client
    image: plaidinc/pattern-client:1.0.7
    ports:
      - 3001:3001
    environment:
      REACT_APP_PLAID_ENV: ${PLAID_ENV}
      REACT_APP_SERVER: http://localhost:5001
      REACT_APP_SERVER_PORT: 5001
    depends_on:
      - server
